//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marathon.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckPointService
    {
        public int CheckPointServiceId { get; set; }
        public Nullable<int> CheckPointId { get; set; }
        public Nullable<int> ServiceId { get; set; }
    
        public virtual CheckPoint CheckPoint { get; set; }
        public virtual ServicesProvided ServicesProvided { get; set; }
    }
}
