//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marathon.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistanceObjects
    {
        public int ObjectId { get; set; }
        public string ObjectName { get; set; }
        public string PhotoName { get; set; }
        public string Distance { get; set; }
        public byte[] ObjectImage { get; set; }
    }
}
