//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marathon.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaceKitSet
    {
        public int RaceKitSetId { get; set; }
        public string RaceKitOption { get; set; }
        public Nullable<int> SetObjects { get; set; }
    
        public virtual RaceKitOption RaceKitOption1 { get; set; }
        public virtual SetObjects SetObjects1 { get; set; }
    }
}
