//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marathon.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicesProvided
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServicesProvided()
        {
            this.CheckPointService = new HashSet<CheckPointService>();
        }
    
        public int ServiceId { get; set; }
        public string ServiceName { get; set; }
        public string PhotoName { get; set; }
        public byte[] ServieImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckPointService> CheckPointService { get; set; }
    }
}
