//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marathon.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetObjects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SetObjects()
        {
            this.RaceKitSet = new HashSet<RaceKitSet>();
        }
    
        public int ObjectId { get; set; }
        public string ObjectName { get; set; }
        public Nullable<int> ObjectStock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaceKitSet> RaceKitSet { get; set; }
    }
}
